### ISSUE TITLE
Clarifications in the readme for missing fonts and openai keys

### ISSUE THREAD

**Issue by LorenzoBellone** [typefly/TypeFly#1]
Hi! 
First of all, thanks for making this work publicly available, I've found it one of the first works trying to make an actual interface between LLM and a real drone platform.
I wanted to reproduce the code starting from the simulation through the web interface. To do so, I'm using a workstation with Ubuntu 20.04 on it. 
I just wanted to suggest some clarifications due to some errors I got before being able to access the GUI. 
The first error I got is the following:
```
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/home/lorenzo/miniconda3/envs/typefly/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/lorenzo/miniconda3/envs/typefly/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lorenzo/LLM/TypeFly/controller/llm_controller.py", line 157, in capture_loop
    YoloClient.plot_results(latest_yolo_result[0], latest_yolo_result[1]['result'])
  File "/home/lorenzo/LLM/TypeFly/controller/yolo_client.py", line 57, in plot_results
    font = ImageFont.truetype("/System/Library/Fonts/Helvetica.ttc", size=50)
  File "/home/lorenzo/miniconda3/envs/typefly/lib/python3.9/site-packages/PIL/ImageFont.py", line 819, in truetype
    return freetype(font)
  File "/home/lorenzo/miniconda3/envs/typefly/lib/python3.9/site-packages/PIL/ImageFont.py", line 816, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/home/lorenzo/miniconda3/envs/typefly/lib/python3.9/site-packages/PIL/ImageFont.py", line 245, in __init__
    self.font = core.getfont(
OSError: cannot open resource
``` 
In order to fix that, I had to modify line 57 in `yolo_client.py` to a font that was available on my system. In my case it was `/usr/share/fonts/truetype/freefont/FreeMono.ttf`. I think that just a clarification in the README would be enough, to warn the users to be careful about the font they are using.

The second error (quite obvious) was the undefined environment variable `OPENAI_API_KEY`. Maybe one could add a check before running the script, if this variable is specified, just to avoid running into this error.

After these two fixes I was able to interact with the interface, and the planning looks very interesting! I will now try to use it on an actual platform, I'm thrilled to see how it works in reality :D 

Cheers,

Lorenzo

**Comment by Leonana69** [comment]
Thanks for your feedback, they are fixed now.
